- name: "Avoid replacing search entry in /etc/resolv.conf"
  hosts: "all"
  tasks:
  - name: "add the correct search entry in /etc/resolv.conf"
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^search'
      line: 'search mycompany.com'
  - name: "update the peerdns in ifcfg-eth0"
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: '^PEERDNS'
      line: 'PEERDNS=no'
